lib/holiday_app_web/router.ex
defmodule HolidayAppWeb.Router do
  use HolidayAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HolidayAppWeb.AuthPipeline
  end

  scope "/", HolidayAppWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end

  scope "/auth", HolidayAppWeb do
    pipe_through :browser

    get "/new", AuthController, :new
    get "/:provider", AuthController, :request
    post "/identity/callback", AuthController, :callback
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", HolidayAppWeb do
    pipe_through [:browser, Guardian.Plug.EnsureAuthenticated]

    delete "/auth/logout", AuthController, :logout
    resources "/holidays", HolidayController
    resources "/users", UserController, only: [:index, :show]
  end
end

lib/holiday_app_web/views/layout_view.ex
defmodule HolidayAppWeb.LayoutView do
  use HolidayAppWeb, :view

  def logged_in?(conn), do: conn.assigns[:current_user]
end

lib/holiday_app_web/templates/layout/_header.html.eex
<div class="container">
  <%= if logged_in?(@conn) do %>
    <span>
      <%= link "Holidays", to: holiday_path(@conn, :index)%>
    </span>
    |
    <span>
      <%= link "Users", to: user_path(@conn, :index)%>
    </span>
    |
    <span>
      <%= link "Logout", to: auth_path(@conn, :logout), method: :delete %>
    </span>
  <% else %>
    <span>
      <%= link "Login", to: auth_path(@conn, :new)%>
    </span>
  <% end %>
</div>

lib/holiday_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Holidays</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "_header.html", assigns %>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>